### PR TITLE
Gsoc/adaptive question

### PR DESCRIPTION
**Pull request by zhjiang1103**
GSOC24/adaptive question

### CODE REVIEW

**Comment by grugna** [comment]
@skyzhangty What is the behavior if the new config file doesn't exist? Does it show everything as it it now without priority? Or will it break the UI?

**Comment by skyzhangty** [comment]
> @skyzhangty What is the behavior if the new config file doesn't exist? Does it show everything as it it now without priority? Or will it break the UI?

@grugna It's going to show everything as it is now.

**Comment by grugna** [comment]
Cool, so the presence or absence of that config in the S3 bucket would change the page and there is no other config or env variable to update?

If so, and if this PR looks good to you feel free to merge it.

**Review by skyzhangty — APPROVED** [review]

**Comment by skyzhangty** [comment]
> Cool, so the presence or absence of that config in the S3 bucket would change the page and there is no other config or env variable to update?
> 
> If so, and if this PR looks good to you feel free to merge it.

@grugna Only one S3 bucket config file. I will merge the PR.

**Pull request merged**
